version = 1

[[analyzers]]
name = "shell"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "nightly"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "cxx"

[[transformers]]
name = "rustfmt"

[[transformers]]
name = "clang-format"